Update svelte-search, use new removeFormAriaAttributes option & alway…
metonym/svelte-typeahead pull request #20
Opened 2021-03-15 21:03 UTC by Skovvart

…s include ul, update activedescendant

More info on #18 and linked items

2021-03-15 22:21 UTC, metonym requested changes
This looks great. One requested change

2021-03-15 22:21 UTC, metonym commented on src/Typeahead.svelte
> +    aria-activedescendant={selectedIndex >= 0 && !hideDropdown ? `${id}-result-${selectedIndex}` : null}
```suggestion
    aria-activedescendant={selectedIndex >= 0 && !hideDropdown && results.length > 0 ? `${id}-result-${selectedIndex}` : null}
```

There is an edge case where the `aria-activedescendant` has a value when the search field is cleared.

To reproduce:

- Search a value with results
- Clear the value by selecting the text and pressing backspace
- **Unexpected**: the `aria-activedescendant` is set to the first list item id

The solution would be to also check that the results length is greater than zero.

2021-03-16 06:41 UTC, Skovvart commented
> This looks great. One requested change

Change applied :-)

2021-03-16 12:40 UTC, metonym approved these changes
This is great work! Thank you for getting to the bottom of this

2021-03-16 12:40 UTC, merged